version: "3.1"
services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - study_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root
      - MYSQL_DATABASE=person
      - MYSQL_USER=henrique
      - MYSQL_PASSWORD=mypass

networks:
  study_mysql: